// Import
const mongoose = require('mongoose')



// Schema method: Creation of a data schema for a book, for the MongoDB database 
// Note: id automatically generated by mongoose
const bookSchema = mongoose.Schema({
    userId: { type: String, required: true },
    title: { type: String, required: true },
    author: { type: String, required: true },
    imageUrl: { type: String, required: true },
    year: { type: Number, required: true },
    genre: { type: String, required: true },
    ratings: [{
        userId: { type: String, required: true },
        grade: { 
            type: Number, 
            required: true, 
            min: 0,
            max: 5
        },
    }],
    averageRating: { type: Number, required: true },
})



// Export the Book model and make it usable with the model method
module.exports = mongoose.model('Book', bookSchema)